/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardProfileIndexRouteImport } from './routes/dashboard/profile/index'
import { Route as DashboardAnalyticsIndexRouteImport } from './routes/dashboard/analytics/index'
import { Route as AuthVerifyMfaIndexRouteImport } from './routes/auth/verify-mfa/index'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/signup/index'
import { Route as AuthSigninIndexRouteImport } from './routes/auth/signin/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/dashboard/users/',
  path: '/dashboard/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/dashboard/settings/',
  path: '/dashboard/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileIndexRoute = DashboardProfileIndexRouteImport.update({
  id: '/dashboard/profile/',
  path: '/dashboard/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAnalyticsIndexRoute = DashboardAnalyticsIndexRouteImport.update({
  id: '/dashboard/analytics/',
  path: '/dashboard/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyMfaIndexRoute = AuthVerifyMfaIndexRouteImport.update({
  id: '/auth/verify-mfa/',
  path: '/auth/verify-mfa/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/auth/signup/',
  path: '/auth/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninIndexRoute = AuthSigninIndexRouteImport.update({
  id: '/auth/signin/',
  path: '/auth/signin/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/signin/': typeof AuthSigninIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/auth/verify-mfa/': typeof AuthVerifyMfaIndexRoute
  '/dashboard/analytics/': typeof DashboardAnalyticsIndexRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/signin': typeof AuthSigninIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/auth/verify-mfa': typeof AuthVerifyMfaIndexRoute
  '/dashboard/analytics': typeof DashboardAnalyticsIndexRoute
  '/dashboard/profile': typeof DashboardProfileIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/signin/': typeof AuthSigninIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/auth/verify-mfa/': typeof AuthVerifyMfaIndexRoute
  '/dashboard/analytics/': typeof DashboardAnalyticsIndexRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/'
    | '/auth/signin/'
    | '/auth/signup/'
    | '/auth/verify-mfa/'
    | '/dashboard/analytics/'
    | '/dashboard/profile/'
    | '/dashboard/settings/'
    | '/dashboard/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/verify-mfa'
    | '/dashboard/analytics'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/users'
  id:
    | '__root__'
    | '/'
    | '/dashboard/'
    | '/auth/signin/'
    | '/auth/signup/'
    | '/auth/verify-mfa/'
    | '/dashboard/analytics/'
    | '/dashboard/profile/'
    | '/dashboard/settings/'
    | '/dashboard/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  AuthSigninIndexRoute: typeof AuthSigninIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
  AuthVerifyMfaIndexRoute: typeof AuthVerifyMfaIndexRoute
  DashboardAnalyticsIndexRoute: typeof DashboardAnalyticsIndexRoute
  DashboardProfileIndexRoute: typeof DashboardProfileIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/dashboard/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile/': {
      id: '/dashboard/profile/'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile/'
      preLoaderRoute: typeof DashboardProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/analytics/': {
      id: '/dashboard/analytics/'
      path: '/dashboard/analytics'
      fullPath: '/dashboard/analytics/'
      preLoaderRoute: typeof DashboardAnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-mfa/': {
      id: '/auth/verify-mfa/'
      path: '/auth/verify-mfa'
      fullPath: '/auth/verify-mfa/'
      preLoaderRoute: typeof AuthVerifyMfaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/auth/signup'
      fullPath: '/auth/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin/': {
      id: '/auth/signin/'
      path: '/auth/signin'
      fullPath: '/auth/signin/'
      preLoaderRoute: typeof AuthSigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  AuthSigninIndexRoute: AuthSigninIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
  AuthVerifyMfaIndexRoute: AuthVerifyMfaIndexRoute,
  DashboardAnalyticsIndexRoute: DashboardAnalyticsIndexRoute,
  DashboardProfileIndexRoute: DashboardProfileIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
