/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as UserDashboardIndexRouteImport } from './routes/user/dashboard/index'
import { Route as Super_adminDashboardIndexRouteImport } from './routes/super_admin/dashboard/index'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardProfileIndexRouteImport } from './routes/dashboard/profile/index'
import { Route as DashboardAnalyticsIndexRouteImport } from './routes/dashboard/analytics/index'
import { Route as AuthVerifyMfaIndexRouteImport } from './routes/auth/verify-mfa/index'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/signup/index'
import { Route as AuthSigninIndexRouteImport } from './routes/auth/signin/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as UserDashboardUsersIndexRouteImport } from './routes/user/dashboard/users/index'
import { Route as UserDashboardSettingsIndexRouteImport } from './routes/user/dashboard/settings/index'
import { Route as UserDashboardProfileIndexRouteImport } from './routes/user/dashboard/profile/index'
import { Route as UserDashboardAnalyticsIndexRouteImport } from './routes/user/dashboard/analytics/index'
import { Route as Super_adminDashboardUsersIndexRouteImport } from './routes/super_admin/dashboard/users/index'
import { Route as Super_adminDashboardSettingsIndexRouteImport } from './routes/super_admin/dashboard/settings/index'
import { Route as Super_adminDashboardProfileIndexRouteImport } from './routes/super_admin/dashboard/profile/index'
import { Route as Super_adminDashboardAnalyticsIndexRouteImport } from './routes/super_admin/dashboard/analytics/index'
import { Route as AdminDashboardUsersIndexRouteImport } from './routes/admin/dashboard/users/index'
import { Route as AdminDashboardSettingsIndexRouteImport } from './routes/admin/dashboard/settings/index'
import { Route as AdminDashboardProfileIndexRouteImport } from './routes/admin/dashboard/profile/index'
import { Route as AdminDashboardAnalyticsIndexRouteImport } from './routes/admin/dashboard/analytics/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDashboardIndexRoute = UserDashboardIndexRouteImport.update({
  id: '/user/dashboard/',
  path: '/user/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const Super_adminDashboardIndexRoute =
  Super_adminDashboardIndexRouteImport.update({
    id: '/super_admin/dashboard/',
    path: '/super_admin/dashboard/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/dashboard/users/',
  path: '/dashboard/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/dashboard/settings/',
  path: '/dashboard/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileIndexRoute = DashboardProfileIndexRouteImport.update({
  id: '/dashboard/profile/',
  path: '/dashboard/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAnalyticsIndexRoute = DashboardAnalyticsIndexRouteImport.update({
  id: '/dashboard/analytics/',
  path: '/dashboard/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyMfaIndexRoute = AuthVerifyMfaIndexRouteImport.update({
  id: '/auth/verify-mfa/',
  path: '/auth/verify-mfa/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/auth/signup/',
  path: '/auth/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninIndexRoute = AuthSigninIndexRouteImport.update({
  id: '/auth/signin/',
  path: '/auth/signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/admin/dashboard/',
  path: '/admin/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDashboardUsersIndexRoute = UserDashboardUsersIndexRouteImport.update({
  id: '/user/dashboard/users/',
  path: '/user/dashboard/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDashboardSettingsIndexRoute =
  UserDashboardSettingsIndexRouteImport.update({
    id: '/user/dashboard/settings/',
    path: '/user/dashboard/settings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserDashboardProfileIndexRoute =
  UserDashboardProfileIndexRouteImport.update({
    id: '/user/dashboard/profile/',
    path: '/user/dashboard/profile/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserDashboardAnalyticsIndexRoute =
  UserDashboardAnalyticsIndexRouteImport.update({
    id: '/user/dashboard/analytics/',
    path: '/user/dashboard/analytics/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Super_adminDashboardUsersIndexRoute =
  Super_adminDashboardUsersIndexRouteImport.update({
    id: '/super_admin/dashboard/users/',
    path: '/super_admin/dashboard/users/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Super_adminDashboardSettingsIndexRoute =
  Super_adminDashboardSettingsIndexRouteImport.update({
    id: '/super_admin/dashboard/settings/',
    path: '/super_admin/dashboard/settings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Super_adminDashboardProfileIndexRoute =
  Super_adminDashboardProfileIndexRouteImport.update({
    id: '/super_admin/dashboard/profile/',
    path: '/super_admin/dashboard/profile/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Super_adminDashboardAnalyticsIndexRoute =
  Super_adminDashboardAnalyticsIndexRouteImport.update({
    id: '/super_admin/dashboard/analytics/',
    path: '/super_admin/dashboard/analytics/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDashboardUsersIndexRoute =
  AdminDashboardUsersIndexRouteImport.update({
    id: '/admin/dashboard/users/',
    path: '/admin/dashboard/users/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDashboardSettingsIndexRoute =
  AdminDashboardSettingsIndexRouteImport.update({
    id: '/admin/dashboard/settings/',
    path: '/admin/dashboard/settings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDashboardProfileIndexRoute =
  AdminDashboardProfileIndexRouteImport.update({
    id: '/admin/dashboard/profile/',
    path: '/admin/dashboard/profile/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDashboardAnalyticsIndexRoute =
  AdminDashboardAnalyticsIndexRouteImport.update({
    id: '/admin/dashboard/analytics/',
    path: '/admin/dashboard/analytics/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/auth/signin/': typeof AuthSigninIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/auth/verify-mfa/': typeof AuthVerifyMfaIndexRoute
  '/dashboard/analytics/': typeof DashboardAnalyticsIndexRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/super_admin/dashboard/': typeof Super_adminDashboardIndexRoute
  '/user/dashboard/': typeof UserDashboardIndexRoute
  '/admin/dashboard/analytics/': typeof AdminDashboardAnalyticsIndexRoute
  '/admin/dashboard/profile/': typeof AdminDashboardProfileIndexRoute
  '/admin/dashboard/settings/': typeof AdminDashboardSettingsIndexRoute
  '/admin/dashboard/users/': typeof AdminDashboardUsersIndexRoute
  '/super_admin/dashboard/analytics/': typeof Super_adminDashboardAnalyticsIndexRoute
  '/super_admin/dashboard/profile/': typeof Super_adminDashboardProfileIndexRoute
  '/super_admin/dashboard/settings/': typeof Super_adminDashboardSettingsIndexRoute
  '/super_admin/dashboard/users/': typeof Super_adminDashboardUsersIndexRoute
  '/user/dashboard/analytics/': typeof UserDashboardAnalyticsIndexRoute
  '/user/dashboard/profile/': typeof UserDashboardProfileIndexRoute
  '/user/dashboard/settings/': typeof UserDashboardSettingsIndexRoute
  '/user/dashboard/users/': typeof UserDashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/auth/signin': typeof AuthSigninIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/auth/verify-mfa': typeof AuthVerifyMfaIndexRoute
  '/dashboard/analytics': typeof DashboardAnalyticsIndexRoute
  '/dashboard/profile': typeof DashboardProfileIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/super_admin/dashboard': typeof Super_adminDashboardIndexRoute
  '/user/dashboard': typeof UserDashboardIndexRoute
  '/admin/dashboard/analytics': typeof AdminDashboardAnalyticsIndexRoute
  '/admin/dashboard/profile': typeof AdminDashboardProfileIndexRoute
  '/admin/dashboard/settings': typeof AdminDashboardSettingsIndexRoute
  '/admin/dashboard/users': typeof AdminDashboardUsersIndexRoute
  '/super_admin/dashboard/analytics': typeof Super_adminDashboardAnalyticsIndexRoute
  '/super_admin/dashboard/profile': typeof Super_adminDashboardProfileIndexRoute
  '/super_admin/dashboard/settings': typeof Super_adminDashboardSettingsIndexRoute
  '/super_admin/dashboard/users': typeof Super_adminDashboardUsersIndexRoute
  '/user/dashboard/analytics': typeof UserDashboardAnalyticsIndexRoute
  '/user/dashboard/profile': typeof UserDashboardProfileIndexRoute
  '/user/dashboard/settings': typeof UserDashboardSettingsIndexRoute
  '/user/dashboard/users': typeof UserDashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/auth/signin/': typeof AuthSigninIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/auth/verify-mfa/': typeof AuthVerifyMfaIndexRoute
  '/dashboard/analytics/': typeof DashboardAnalyticsIndexRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/super_admin/dashboard/': typeof Super_adminDashboardIndexRoute
  '/user/dashboard/': typeof UserDashboardIndexRoute
  '/admin/dashboard/analytics/': typeof AdminDashboardAnalyticsIndexRoute
  '/admin/dashboard/profile/': typeof AdminDashboardProfileIndexRoute
  '/admin/dashboard/settings/': typeof AdminDashboardSettingsIndexRoute
  '/admin/dashboard/users/': typeof AdminDashboardUsersIndexRoute
  '/super_admin/dashboard/analytics/': typeof Super_adminDashboardAnalyticsIndexRoute
  '/super_admin/dashboard/profile/': typeof Super_adminDashboardProfileIndexRoute
  '/super_admin/dashboard/settings/': typeof Super_adminDashboardSettingsIndexRoute
  '/super_admin/dashboard/users/': typeof Super_adminDashboardUsersIndexRoute
  '/user/dashboard/analytics/': typeof UserDashboardAnalyticsIndexRoute
  '/user/dashboard/profile/': typeof UserDashboardProfileIndexRoute
  '/user/dashboard/settings/': typeof UserDashboardSettingsIndexRoute
  '/user/dashboard/users/': typeof UserDashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/'
    | '/admin/dashboard/'
    | '/auth/signin/'
    | '/auth/signup/'
    | '/auth/verify-mfa/'
    | '/dashboard/analytics/'
    | '/dashboard/profile/'
    | '/dashboard/settings/'
    | '/dashboard/users/'
    | '/super_admin/dashboard/'
    | '/user/dashboard/'
    | '/admin/dashboard/analytics/'
    | '/admin/dashboard/profile/'
    | '/admin/dashboard/settings/'
    | '/admin/dashboard/users/'
    | '/super_admin/dashboard/analytics/'
    | '/super_admin/dashboard/profile/'
    | '/super_admin/dashboard/settings/'
    | '/super_admin/dashboard/users/'
    | '/user/dashboard/analytics/'
    | '/user/dashboard/profile/'
    | '/user/dashboard/settings/'
    | '/user/dashboard/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/admin/dashboard'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/verify-mfa'
    | '/dashboard/analytics'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/super_admin/dashboard'
    | '/user/dashboard'
    | '/admin/dashboard/analytics'
    | '/admin/dashboard/profile'
    | '/admin/dashboard/settings'
    | '/admin/dashboard/users'
    | '/super_admin/dashboard/analytics'
    | '/super_admin/dashboard/profile'
    | '/super_admin/dashboard/settings'
    | '/super_admin/dashboard/users'
    | '/user/dashboard/analytics'
    | '/user/dashboard/profile'
    | '/user/dashboard/settings'
    | '/user/dashboard/users'
  id:
    | '__root__'
    | '/'
    | '/dashboard/'
    | '/admin/dashboard/'
    | '/auth/signin/'
    | '/auth/signup/'
    | '/auth/verify-mfa/'
    | '/dashboard/analytics/'
    | '/dashboard/profile/'
    | '/dashboard/settings/'
    | '/dashboard/users/'
    | '/super_admin/dashboard/'
    | '/user/dashboard/'
    | '/admin/dashboard/analytics/'
    | '/admin/dashboard/profile/'
    | '/admin/dashboard/settings/'
    | '/admin/dashboard/users/'
    | '/super_admin/dashboard/analytics/'
    | '/super_admin/dashboard/profile/'
    | '/super_admin/dashboard/settings/'
    | '/super_admin/dashboard/users/'
    | '/user/dashboard/analytics/'
    | '/user/dashboard/profile/'
    | '/user/dashboard/settings/'
    | '/user/dashboard/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AuthSigninIndexRoute: typeof AuthSigninIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
  AuthVerifyMfaIndexRoute: typeof AuthVerifyMfaIndexRoute
  DashboardAnalyticsIndexRoute: typeof DashboardAnalyticsIndexRoute
  DashboardProfileIndexRoute: typeof DashboardProfileIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
  Super_adminDashboardIndexRoute: typeof Super_adminDashboardIndexRoute
  UserDashboardIndexRoute: typeof UserDashboardIndexRoute
  AdminDashboardAnalyticsIndexRoute: typeof AdminDashboardAnalyticsIndexRoute
  AdminDashboardProfileIndexRoute: typeof AdminDashboardProfileIndexRoute
  AdminDashboardSettingsIndexRoute: typeof AdminDashboardSettingsIndexRoute
  AdminDashboardUsersIndexRoute: typeof AdminDashboardUsersIndexRoute
  Super_adminDashboardAnalyticsIndexRoute: typeof Super_adminDashboardAnalyticsIndexRoute
  Super_adminDashboardProfileIndexRoute: typeof Super_adminDashboardProfileIndexRoute
  Super_adminDashboardSettingsIndexRoute: typeof Super_adminDashboardSettingsIndexRoute
  Super_adminDashboardUsersIndexRoute: typeof Super_adminDashboardUsersIndexRoute
  UserDashboardAnalyticsIndexRoute: typeof UserDashboardAnalyticsIndexRoute
  UserDashboardProfileIndexRoute: typeof UserDashboardProfileIndexRoute
  UserDashboardSettingsIndexRoute: typeof UserDashboardSettingsIndexRoute
  UserDashboardUsersIndexRoute: typeof UserDashboardUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/dashboard/': {
      id: '/user/dashboard/'
      path: '/user/dashboard'
      fullPath: '/user/dashboard/'
      preLoaderRoute: typeof UserDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super_admin/dashboard/': {
      id: '/super_admin/dashboard/'
      path: '/super_admin/dashboard'
      fullPath: '/super_admin/dashboard/'
      preLoaderRoute: typeof Super_adminDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/dashboard/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile/': {
      id: '/dashboard/profile/'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile/'
      preLoaderRoute: typeof DashboardProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/analytics/': {
      id: '/dashboard/analytics/'
      path: '/dashboard/analytics'
      fullPath: '/dashboard/analytics/'
      preLoaderRoute: typeof DashboardAnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-mfa/': {
      id: '/auth/verify-mfa/'
      path: '/auth/verify-mfa'
      fullPath: '/auth/verify-mfa/'
      preLoaderRoute: typeof AuthVerifyMfaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/auth/signup'
      fullPath: '/auth/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin/': {
      id: '/auth/signin/'
      path: '/auth/signin'
      fullPath: '/auth/signin/'
      preLoaderRoute: typeof AuthSigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/dashboard/users/': {
      id: '/user/dashboard/users/'
      path: '/user/dashboard/users'
      fullPath: '/user/dashboard/users/'
      preLoaderRoute: typeof UserDashboardUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/dashboard/settings/': {
      id: '/user/dashboard/settings/'
      path: '/user/dashboard/settings'
      fullPath: '/user/dashboard/settings/'
      preLoaderRoute: typeof UserDashboardSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/dashboard/profile/': {
      id: '/user/dashboard/profile/'
      path: '/user/dashboard/profile'
      fullPath: '/user/dashboard/profile/'
      preLoaderRoute: typeof UserDashboardProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/dashboard/analytics/': {
      id: '/user/dashboard/analytics/'
      path: '/user/dashboard/analytics'
      fullPath: '/user/dashboard/analytics/'
      preLoaderRoute: typeof UserDashboardAnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super_admin/dashboard/users/': {
      id: '/super_admin/dashboard/users/'
      path: '/super_admin/dashboard/users'
      fullPath: '/super_admin/dashboard/users/'
      preLoaderRoute: typeof Super_adminDashboardUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super_admin/dashboard/settings/': {
      id: '/super_admin/dashboard/settings/'
      path: '/super_admin/dashboard/settings'
      fullPath: '/super_admin/dashboard/settings/'
      preLoaderRoute: typeof Super_adminDashboardSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super_admin/dashboard/profile/': {
      id: '/super_admin/dashboard/profile/'
      path: '/super_admin/dashboard/profile'
      fullPath: '/super_admin/dashboard/profile/'
      preLoaderRoute: typeof Super_adminDashboardProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super_admin/dashboard/analytics/': {
      id: '/super_admin/dashboard/analytics/'
      path: '/super_admin/dashboard/analytics'
      fullPath: '/super_admin/dashboard/analytics/'
      preLoaderRoute: typeof Super_adminDashboardAnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/users/': {
      id: '/admin/dashboard/users/'
      path: '/admin/dashboard/users'
      fullPath: '/admin/dashboard/users/'
      preLoaderRoute: typeof AdminDashboardUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/settings/': {
      id: '/admin/dashboard/settings/'
      path: '/admin/dashboard/settings'
      fullPath: '/admin/dashboard/settings/'
      preLoaderRoute: typeof AdminDashboardSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/profile/': {
      id: '/admin/dashboard/profile/'
      path: '/admin/dashboard/profile'
      fullPath: '/admin/dashboard/profile/'
      preLoaderRoute: typeof AdminDashboardProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/analytics/': {
      id: '/admin/dashboard/analytics/'
      path: '/admin/dashboard/analytics'
      fullPath: '/admin/dashboard/analytics/'
      preLoaderRoute: typeof AdminDashboardAnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AuthSigninIndexRoute: AuthSigninIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
  AuthVerifyMfaIndexRoute: AuthVerifyMfaIndexRoute,
  DashboardAnalyticsIndexRoute: DashboardAnalyticsIndexRoute,
  DashboardProfileIndexRoute: DashboardProfileIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
  Super_adminDashboardIndexRoute: Super_adminDashboardIndexRoute,
  UserDashboardIndexRoute: UserDashboardIndexRoute,
  AdminDashboardAnalyticsIndexRoute: AdminDashboardAnalyticsIndexRoute,
  AdminDashboardProfileIndexRoute: AdminDashboardProfileIndexRoute,
  AdminDashboardSettingsIndexRoute: AdminDashboardSettingsIndexRoute,
  AdminDashboardUsersIndexRoute: AdminDashboardUsersIndexRoute,
  Super_adminDashboardAnalyticsIndexRoute:
    Super_adminDashboardAnalyticsIndexRoute,
  Super_adminDashboardProfileIndexRoute: Super_adminDashboardProfileIndexRoute,
  Super_adminDashboardSettingsIndexRoute:
    Super_adminDashboardSettingsIndexRoute,
  Super_adminDashboardUsersIndexRoute: Super_adminDashboardUsersIndexRoute,
  UserDashboardAnalyticsIndexRoute: UserDashboardAnalyticsIndexRoute,
  UserDashboardProfileIndexRoute: UserDashboardProfileIndexRoute,
  UserDashboardSettingsIndexRoute: UserDashboardSettingsIndexRoute,
  UserDashboardUsersIndexRoute: UserDashboardUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
